name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 14 * * 1"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    permissions:
      id-token: write
      contents: write
      security-events: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }} .
      
      - name: Run image tests
        run: |
          docker run --rm -it -p 5000:5000 -d ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }} mlflow server --host 0.0.0.0
          sleep 5
          curl -I --fail localhost:5000

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_CHARMED_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_CHARMED_ACCESS_TOKEN }}
      
      - name: Docker push image to DockerHub
        run: |
          docker tag ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:${{ github.sha }} ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:latest
          docker push ${{ vars.DOCKER_HUB_CHARMED_IMAGE }}:latest
